# Loads default set of integrations. Do not remove.
default_config:

#homeassistant:
#  internal_url: !env_var INTERNAL_URL
logger:
  default: info
  logs:
    async_reolink.rest: debug
    async_reolink.api: debug
    custom_components.reolink_rest: debug


# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy: